### ISSUE TITLE
Nondeterminism reported for DTMC JANI model

### ISSUE THREAD

**Issue by hobborg** [utwente-fmt/DFTRES#1]
The [QComp 2020 benchmarks](http://qcomp.org/competition/2020/benchmarks.html) include several DTMC models, among them the [coupons.9-4](http://qcomp.org/benchmarks/dtmc/coupon/coupon.9-4.jani) JANI file.<br>
When running DFTRES on that file with the following command line, "nondeterminism" is reported in a probabilistic transition, even though the JANI file is of type DTMC.
```
java -jar DFTRES.jar --progress -s 0 --relErr 5e-2 --prop collect_all_bounded --def B 5 coupon.9-4.jani
```

**Comment by hobborg** [comment]
The **coupons** JANI model was generated by Storm from a PGCL file, so I was suspecting the issue could be related to the PGCL &rarr; JANI translation.<br>
However, the same issue occurs with DTMCs that were converted from PRISM models, e.g. [crowds](http://qcomp.org/benchmarks/index.html#crowds) using the following command:
```
java -jar DFTRES.jar -s 0 --relErr 5e-2 --prop collect_all_bounded --def TotalRuns 5 --def CrowdSize 10 crowds.jani
```

**Comment by ennoruijters** [comment]
Fixed, the nondeterminism detection wasn't properly resetting between states and wrongly detecting both interactive and probabilistic transitions. Crowds now works (coupons parses but the property is unsupported).
