### ISSUE TITLE
Interrupt signal handling

### ISSUE THREAD

**Issue by hobborg** [utwente-fmt/DFTRES#4]
Add shutdown hook to Main routine, to handle SIGINT and other early interruptions in which it would be possible to return a partial result.<br>
This requires sharing the results array between Main and the Simulator class. More specifically, the current variable
```java
ArrayList<SimulationResult> results
```
cannot be a return value of the simulation routines in the `Simulator` class (namely `sim()`, `simRelError()`, and `simUnsafeRelError()`). These routines must take such variable as a parameter, and fill it constantly with the results produced.<br>
The computation of the CI can be done either on each update of a trace, or just once by the `showResults()` routine in Main.

@ennoruijters Please comment if you find this incorrect, or if you see an easier way around.

**Comment by ennoruijters** [comment]
It might be simpler and/or cleaner to keep the TraceGenerator(s) as fields of Simulator and stop creating new ones for every simulation batch; that could also improve the unsafe relative-error simulation by not dropping the results of previous batches.

It should be fine to get results of a batch of TraceGenerators multiple times (except I don't think this has been tested before), and computing results just when Main needs them should be fine, except possible slightly incorrect if you get extremely unlucky and access them just while they are being updated after a run (unless some form of synchronisation is added).

**Comment by hobborg** [comment]
Great! On it.
Will probably leave proper sync as TODO comment, but let's see.

**Comment by hobborg** [comment]
Implemented in 3879b0f.
@ennoruijters If you will, at some point, revise the changes in 3879b0f and try to incorporate them to master.
